{% set name = "jupyter-themer" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67de747b431c869e780453adf08d396cf911e94e37dbf36ce7ff0d6d9e7f09d3

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jupyter-themer = jupythemer.jupythemer:run

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jupyter
    - notebook

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupythemer

  commands:
    - jupyter-themer --help

about:
  home: https://github.com/transcranial/jupyter-themer
  # No MANIFEST - see https://github.com/transcranial/jupyter-themer/pull/25
  license_file:  LICENSE
  license: MIT
  license_family: MIT
  summary: 'Custom CSS themer for jupyter notebooks'
  dev_url: https://github.com/transcranial/jupyter-themer

extra:
  recipe-maintainers:
    - pmlandwehr
