travis:
  secure:
    BINSTAR_TOKEN: TwwlBmN7Sz1kBtrL5s5Qhzi3r72iryYvCF2WLctJNfFNp08a8FpvxLYiFYldeAF+qGetWXjOGXD/quCUQdiwv9FDwpRUgrxdrKPT9RsLiuXJBhkIyfh7SvHGZR+GAU6RTO3VqwXLZ4gOfsCA3y+UPSN1t3Accv7FxtFgXF0Kv/yeodw5PFP6CFyNOHTXW50vJcTsAaXgF9JucHZ6qW6PSjzzVVh4ha2SCASC7qDZRSf/DMzmm6rJLm4FYUPlYEJP8e607UIO3KLTbMOANfAzP55Ybb7gSDEAnMAB7qA0mMaPBAxT5xv2VcwU3ZngJjEYgSuQivusMaRvIEuwXnEN0qDDPargnIpipGacVcwC1u4a/Vb+yficFrYwuLBRWkUNd6qtlguq3Dz+qOve3eZwrmxqhvIUW/zSwzGA3WEfE8vFAG8SxwRaU8yJ7BUErdVeP/cjyurP1xlD6XuJ9GmcphbaJoPc1MdGm3iYzAMvHZtg1nPe/HSS6hQ7cUAXFRKcE05DavzRY6k8jwBTw5ofBdKbRuQPhVOis3pTNv3KyUPhMc+dU+G6b1yENQ66tOCVOKBigGp2QRvkjxD1VnCnmq73ArlTcDVT2TItioPcDv3Wjp0aI/Tx6tw3fW3eeL9hY09NkNc4AIb/l9epRZolmFX1VjRInL40+8T8dzHzV5w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
