travis:
  secure:
    BINSTAR_TOKEN: OCKmIcslZgql54QlWtQWnFSck0XDY82E5dtYLgq7zjynjG3luCU9VQs7hGKsAqN35WW8iLcVmt64T5c8dGHm2SG9BbUid2eTFGn63+c+7cc9WpFS3Lyx0+slaI5FQv8f7F4cdGX1S4DNRohJppXv+QU0PEq/cbijCIx2YXfyOfVCseTSJ5iDkA9op6BDVFXpnkHM7l3rFRGbBSAlv6La1Obw/+m0lIRsK8xCXa7SjPRDTxLlFkJLnW/mmsGj/wgNHB7ZNX7qqS/dqbvgJTQXP+HBctCQgldQRenDB/RyjgdRz5irMgBXvyq9ZNDqSTbGuGD+fV/ILGC9aI2wB95oNcS15CNeWmmcqxXMLDT2QnKFfK58N06GihangvijLBKYsd1PgMykBqu5IcwY1p1UdjBiZOhnkD7rHrMUxX9I79NiLRUUshAQhcLcXLOkOzaa9+P+GfC0keEgkBQ+yhKQfZdUqC/so1zcayuAQpbZLgD88WwA8hm6xD37Yt6sYfzbMLEPQRo4DG0+U3GgawOXzo4/6PIMrMyJurBlGHxTF63ptuYb9saQ+x7l8gwsRQmYbLzYcItW3HeqTS7HrWro5+zjepUz/9Cuu2wJabhO2EoODHsoSFjYKc6mWIgc53y58PGSp5OaDpf489V3k5SQpBMo48eYCrexI0Zi2hD3nyc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
